const productos = [
  {
    id: 1,
    nombre: "Aparador Uspallata",
    categoria: "Living",
    precio: 850000,
    imagen: "img/productos/aparador-uspallata.png",
    descripcionCorta: "Aparador de seis puertas en nogal sostenible con tiradores metálicos en acabado latón.",
    destacado: false,
  },
  {
    id: 2,
    nombre: "Biblioteca Recoleta",
    categoria: "Living",
    precio: 620000,
    imagen: "img/productos/biblioteca-recoleta.png",
    descripcionCorta: "Sistema modular de estantes abiertos en acero Sage Green y roble claro.",
    destacado: false,
  },
  {
    id: 3,
    nombre: "Butaca Mendoza",
    categoria: "Living",
    precio: 480000,
    imagen: "img/productos/butaca-mendoza.png",
    descripcionCorta: "Butaca tapizada en bouclé Dusty Rose con base de madera de guatambú.",
    destacado: true,
  },
  {
    id: 4,
    nombre: "Sillón Copacabana",
    categoria: "Living",
    precio: 690000,
    imagen: "img/productos/sillon-copacabana.png",
    descripcionCorta: "Sillón lounge en cuero cognac con base giratoria, estética brasilera de los 60.",
    destacado: true,
  },
  {
    id: 5,
    nombre: "Mesa de Centro Araucaria",
    categoria: "Living",
    precio: 410000,
    imagen: "img/productos/mesa-centro-araucaria.png",
    descripcionCorta: "Mesa de centro con sobre de mármol Patagonia y base de tres patas en nogal.",
    destacado: true,
  },
  {
    id: 6,
    nombre: "Mesa de Noche Aconcagua",
    categoria: "Dormitorio",
    precio: 195000,
    imagen: "img/productos/mesa-noche-aconcagua.png",
    descripcionCorta: "Mesa de noche con cajón oculto y repisa inferior en roble certificado FSC.",
    destacado: false,
  },
  {
    id: 7,
    nombre: "Sofá Patagonia",
    categoria: "Living",
    precio: 980000,
    imagen: "img/productos/sofa-patagonia.png",
    descripcionCorta: "Sofá de tres cuerpos en lino Warm Alabaster con patas cónicas de madera.",
    destacado: true,
  },
  {
    id: 8,
    nombre: "Mesa Comedor Pampa",
    categoria: "Comedor",
    precio: 875000,
    imagen: "img/productos/mesa-comedor-pampa.png",
    descripcionCorta: "Mesa extensible de roble macizo, se adapta de 6 a 10 comensales.",
    destacado: false,
  },
  {
    id: 9,
    nombre: "Sillas Córdoba",
    categoria: "Comedor",
    precio: 520000,
    imagen: "img/productos/sillas-cordoba.png",
    descripcionCorta: "Set de 4 sillas apilables en contrachapado de nogal y estructura tubular.",
    destacado: false,
  },
  {
    id: 10,
    nombre: "Escritorio Costa",
    categoria: "Estudio",
    precio: 310000,
    imagen: "img/productos/escritorio-costa.png",
    descripcionCorta: "Escritorio compacto en bambú laminado con cajón organizado y pasacables.",
    destacado: false,
  },
  {
    id: 11,
    nombre: "Silla de Trabajo Belgrano",
    categoria: "Estudio",
    precio: 265000,
    imagen: "img/productos/silla-trabajo-belgrano.png",
    descripcionCorta: "Silla ergonómica regulable con respaldo de malla transpirable.",
    destacado: false,
  },
];